const HTTP_CREATE_STATUS = 201;
const HTTP_OK_STATUS = 200;
const NO_CONTENT = 204;
const BAD_REQUEST = 400;
const UNAUTHORIZED = 401;
const FORBIDDEN = 403;
const HTTP_NOT_FOUND = 404;
const CONFLICT_STATUS = 409;
const UNPROCESSABLE_ENTITY = 422;

module.exports = {
  HTTP_OK_STATUS,
  HTTP_CREATE_STATUS,
  NO_CONTENT,
  BAD_REQUEST,
  UNAUTHORIZED,
  FORBIDDEN,
  HTTP_NOT_FOUND,
  CONFLICT_STATUS,
  UNPROCESSABLE_ENTITY,
};
