const HTTP_SERVER_ERROR = 500;
const HTTP_CONFLICT = 409;
const HTTP_NOT_FOUND = 404;
const HTTP_UNAUTHORIZED = 401;
const HTTP_BAD_REQUEST = 400;
const HTTP_NO_CONTENT = 204;
const HTTP_CREATED = 201;
const HTTP_OK_STATUS = 200;

module.exports = {
  HTTP_SERVER_ERROR,
  HTTP_CONFLICT,
  HTTP_NOT_FOUND,
  HTTP_UNAUTHORIZED,
  HTTP_BAD_REQUEST,
  HTTP_NO_CONTENT,
  HTTP_CREATED,
  HTTP_OK_STATUS,
};