const OK_STATUS = 200;
const CREATED_STATUS = 201;
const BAD_REQUEST = 400;
const UNAUTHORIZED = 401;
const CONFLICT = 409;

module.exports = {
  OK_STATUS,
  CREATED_STATUS,
  BAD_REQUEST,
  CONFLICT,
  UNAUTHORIZED,
};