const STATUS_OK = 200;
const STATUS_CREATE = 201;
const STATUS_BAD_REQUEST = 400;
const STATUS_UNAUTHORIZED = 401;
const STATUS_NOT_FOUND = 404;
const STATUS_UNPROCESSABLE = 422;
const STATUS_CONFLICT = 409;
const STATUS_NO_CONTENT = 204;

module.exports = {
  STATUS_OK,
  STATUS_CREATE,
  STATUS_BAD_REQUEST,
  STATUS_UNAUTHORIZED,
  STATUS_NOT_FOUND,
  STATUS_UNPROCESSABLE,
  STATUS_CONFLICT,
  STATUS_NO_CONTENT,
};
// https://developer.mozilla.org/pt-BR/docs/Web/HTTP/Status