const STATUS_BAD_REQUEST = 400;
const STATUS_CONFLICT = 409;
const STATUS_CREATED = 201;
const STATUS_OK = 200;
const STATUS_NO_CONTENT = 204;

const MSG_ALREADY_REG = 'User already registered';
const MSG_INVALID_FIELDS = 'Invalid fields';

const CONFLICT_ERROR = { status: STATUS_CONFLICT, message: MSG_ALREADY_REG };
const INVALID_FIELDS = { status: STATUS_BAD_REQUEST, message: MSG_INVALID_FIELDS };

module.exports = {
  STATUS_BAD_REQUEST,
  CONFLICT_ERROR,
  STATUS_CREATED,
  STATUS_OK,
  STATUS_NO_CONTENT,
  INVALID_FIELDS,
};