const STATUS_BAD_REQUEST = 400;
const STATUS_UNAUTHORIZED = 401;
const STATUS_NOT_FOUND = 404;
const STATUS_CONFLICT = 409;
const STATUS_CREATED = 201;
const STATUS_OK = 200;
const STATUS_NO_CONTENT = 204;

const MSG_ALREADY_REG = 'User already registered';
const MSG_INVALID_FIELDS = 'Invalid fields';
const MSG_TOKEN_NOT_FOUND = 'Token not found';
const MSG_TOKEN_EXPIRED = 'Expired or invalid token';
const MSG_DOES_NOT_EXIST = 'User does not exist';

const CONFLICT_ERROR = { status: STATUS_CONFLICT, message: MSG_ALREADY_REG };
const INVALID_FIELDS = { status: STATUS_BAD_REQUEST, message: MSG_INVALID_FIELDS };
const USER_DOES_NOT_EXIST = { status: STATUS_NOT_FOUND, message: MSG_DOES_NOT_EXIST };

module.exports = {
  STATUS_BAD_REQUEST,
  STATUS_UNAUTHORIZED,
  CONFLICT_ERROR,
  STATUS_CREATED,
  STATUS_OK,
  STATUS_NO_CONTENT,
  INVALID_FIELDS,
  MSG_TOKEN_NOT_FOUND,
  MSG_TOKEN_EXPIRED,
  USER_DOES_NOT_EXIST,
};